include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # Désactiver certaines règles incompatibles avec l'existant
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    
    # Garder nos règles spécifiques importantes
    always_use_package_imports: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_locals: true
    use_super_parameters: true
    use_key_in_widget_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    sized_box_for_whitespace: true
    avoid_function_literals_in_foreach_calls: true
    prefer_const_constructors_in_immutables: true
    
    # Accessibility
    use_decorated_box: true  # Performance + a11y
    use_colored_box: true    # Performance + a11y

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "tools/**"
    - "tool/**"
    - "scripts/**"
    - "dev_scripts/**"
    - "test_*.dart"
