name: spiritual_routines
description: Application de Routines Spirituelles et d’Invocations (FR/AR) avec IA, hors-ligne, TTS, compteur persistant.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  intl: ^0.20.2
  dio: ^5.5.0+1
  crypto: ^3.0.3
  path: ^1.9.0
  path_provider: ^2.1.4
  collection: ^1.18.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4

  # Audio / TTS
  just_audio: ^0.9.39
  audio_session: ^0.1.21
  audio_service: ^0.18.13
  flutter_tts: ^3.8.3

  # Local databases
  drift: ^2.17.0
  drift_flutter: ^0.1.0
  sqlite3_flutter_libs: ^0.5.24
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # Secure storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3
  local_auth: ^2.2.0
  encrypt: ^5.0.3
  
  # User Experience
  haptic_feedback: ^0.5.1+1
  vibration: ^1.8.4

  # Files / OCR / PDF
  file_picker: ^8.0.3
  google_mlkit_text_recognition: ^0.13.0
  pdfx: ^2.6.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  record: ^6.0.0
  
  # Export & Sharing
  share_plus: ^7.2.2
  csv: ^6.0.0
  pdf: ^3.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  freezed: ^2.4.6
  drift_dev: ^2.17.0
  isar_generator: ^3.0.5
  test: any

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/corpus/
    - assets/images/
    - assets/test_images/
    - assets/tessdata/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
    - family: NotoNaskhArabic
      fonts:
        - asset: assets/fonts/NotoNaskhArabic/NotoNaskhArabic-Regular.ttf
        - asset: assets/fonts/NotoNaskhArabic/NotoNaskhArabic-SemiBold.ttf
          weight: 600
