name: CI/CD Multi-Platform

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    
    - name: Setup FVM
      run: |
        dart pub global activate fvm
        fvm install
        
    - name: Install dependencies
      run: flutter pub get
        
    - name: Generate code
      run: dart run build_runner build --delete-conflicting-outputs
      
    - name: Analyze code
      run: flutter analyze --fatal-infos
      
    - name: Check formatting
      run: dart format --output=none --set-exit-if-changed .
      
    - name: Run tests
      run: flutter test --reporter=github --coverage
      
    - name: Test goldens
      run: bash scripts/goldens.sh test
      
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: coverage/lcov.info

  build-multi-platform:
    needs: quality
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: web
            build-cmd: 'flutter build web --release'
          - os: ubuntu-latest  
            target: android
            build-cmd: 'flutter build apk --release'
          - os: macos-latest
            target: ios
            build-cmd: 'flutter build ios --release --no-codesign'
          - os: macos-latest
            target: macos
            build-cmd: 'flutter build macos --release'
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    
    - name: Setup FVM
      run: |
        dart pub global activate fvm
        fvm install
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Generate code
      run: dart run build_runner build --delete-conflicting-outputs
      
    - name: Build ${{ matrix.target }}
      run: ${{ matrix.build-cmd }}
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.target }}
        path: |
          build/web/
          build/app/outputs/flutter-apk/
          build/ios/iphoneos/
          build/macos/Build/Products/Release/
        retention-days: 7