name: CI/CD

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.8'
        
    - name: Install dependencies
      run: |
        flutter pub get
        dart pub add --dev test
        
    - name: Generate code
      run: dart run build_runner build --delete-conflicting-outputs
      
    - name: Analyze code
      run: flutter analyze --fatal-infos
      
    - name: Check formatting
      run: dart format --output=none --set-exit-if-changed .
      
    - name: Run tests
      run: flutter test --reporter=github --coverage
      
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: coverage/lcov.info